[{
    "company_name":"hcl",
    "date":ISODate("2020-10-16"),
    "students_appeared":"veni,roja,rishi,rita"
},
{
    "company_name":"cts",
    "date":ISODate("2020-10-20"),
    "students_appeared":"veni,roja"
},
{
    "company_name":"tcs",
    "date":ISODate("2020-10-29"),
    "students_appeared":"priya,jaya"
},
{
    "company_name":"zoho",
    "date":ISODate("2020-11-10"),
    "students_appeared":"vimala,viji"
},
{
    "company_name":"guvi",
    "date":ISODate("2020-11-16"),
    "students_appeared":"shiva,gem,nancy"
}]