
[{
    "user_name":"veni",
    "date":ISODate("2020-10-16"),
    "attendance":"absent",
    "task_submission":"failed"
},
{
    "user_name":"raja",
    "date":ISODate("2020-10-20"),
    "attendance":"absent",
    "task_submission":"failed"
},
{
    "user_name":"mala",
    "date":ISODate("2020-10-29"),
    "attendance":"present",
    "task_submission":"passes"
},
{
    "user_name":"rishi",
    "date":ISODate("2020-11-01"),
    "attendance":"absent",
    "task_submission":"failed"
},
{
    "user_name":"rita",
    "date":ISODate("2020-11-16"),
    "attendance":"present",
    "task_submission":"passed"
}]